apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitfaas
  namespace: <REPLACE>
  labels:
    app: gitfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitfaas
  template:
    metadata:
      labels:
        app: gitfaas
    spec:
      shareProcessNamespace: true
      containers:
      - name:  git
        image: wingardiumleviosa/gitfaas/gitfaas-git:0.0.3
        env:
        - name: GIT_URL
          value: "<REPLACE>"
        - name: GIT_USER_NAME
          value: "<REPLACE>"
        - name: GIT_PERSONAL_TOKEN
          value: "<REPLACE>"
        - name: POLLING_TIME
          value: "5"
        - name: WORK_PATH
          value: "/pod-data"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-data
          mountPath: /pod-data

      - name:  apply
        image: wingardiumleviosa/gitfaas/gitfaas-apply:0.0.3
        env:
        - name: WORK_PATH
          value: "/pod-data"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-data
          mountPath: /pod-data
        - name: kubeconfig
          mountPath: "/init"

      volumes:
      - name: shared-data
        emptyDir: {}
      - name: kubeconfig
        secret:
          secretName: kubeconfig
---
apiVersion: v1
kind: Service
metadata:
  name:  gitfaas
  namespace: openfaas-fn
  labels:
    app: gitfaas
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: gitfaas

